# Generated by Django 3.2 on 2021-04-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrowed',
            new_name='borrower',
        ),
    ]
